In [2]:
import sys
sys.path.append('../module/')
from krylov.methods import Methods,plt
import glob

In [3]:
paths = glob.glob('1081/EFG/ada*')
ada_paths = sorted(paths)
paths = glob.glob('1081/EFG/kskip*')
kskip_paths = sorted(paths)

In [4]:
import numpy as np
kskip_list = list()
adaptive_list = list()
for k in range(len(paths)):
    adaptive = Methods(A=np.zeros(1),b=np.zeros(1))
    kskip = Methods(A=np.zeros(1),b=np.zeros(1))
    adaptive.json2instance(ada_paths[k])
    kskip.json2instance(kskip_paths[k])
#     Methods.multiplot([adaptive,kskip],figsize=(12,8))
    if kskip.converged:
        kskip_list.append(str(kskip.solution_updates[kskip.iter-1]))
    else:
        kskip_list.append('発散')
    if adaptive.converged:
        i = 1
        while True:
            tmp = adaptive.solution_updates[adaptive.iter-i]
            if tmp is not 0:
                break
            i += 1
        adaptive_list.append(tmp)
    else:
        adaptive_list.append('発散')

In [5]:
import pandas as pd

/Users/takayasu/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pandas/compat/__init__.py:85: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [6]:
df = pd.DataFrame(
    {
        'k':[k for k in range(1,31)],
        'k-skip':kskip_list,
        'adaptive':adaptive_list
    }
).set_index('k')
df

   k-skip adaptive
k
1    1557     1557
2    1570     1570
3    1613     1613
4    1761     1761
5    1879     1879
6    1989     1989
7    2097     2097
8   19351     8436
9      発散    11290
10     発散     6372
11     発散       発散
12     発散     6204
13     発散     9453
14  27421    18986
15     発散       発散
16     発散     9001
17     発散       発散
18     発散       発散
19     発散       発散
20     発散    34292
21     発散       発散
22     発散       発散
23     発散       発散
24     発散       発散
25     発散       発散
26     発散    10211
27     発散       発散
28     発散       発散
29     発散       発散
30     発散       発散

In [7]:
df.to_csv('table.csv')